version: "2.2"

networks:
  shared:
    name: shared
    external: true

services:
  landing-api:
    build: .
    container_name: sbercoin-landing-backend
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - shared
    command: bash -c "gunicorn api.__main__:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    volumes:
      - ./settings.toml:/usr/local/bin/settings.toml
    environment:
      TZ: "Europe/Moscow"