[winpay]
hour = 11
minute = 30
second = 0
microsecond = 0

timezone = "Europe/Moscow"

[storages]
postgres = "postgres://postgres:postgres@127.0.0.1:5432/postgres"
redis = "redis://127.0.0.1:6379/0"

