[winpay]
hour = 16
minute = 30
second = 0
microsecond = 0

timezone = "Europe/Moscow"

[storages]
postgres = "postgres://sbercoin:sbercoin-password@127.0.0.1:5432/sbercoin"
redis = "redis://127.0.0.1:6379/0"

