[winpay]
hour = 16
minute = 30
second = 0
microsecond = 0

timezone = "Europe/Moscow"

[storages]
postgres = "postgres://sbercoin:sbercoin-password@127.0.0.1:5432/sbercoin"
redis = "redis://127.0.0.1:6379/0"

[sbercoin]
wallet = 'SY2kNKexBwJt1s7cd3KdphdPCGmVoSmbUN'
wallet_pk = '9toyp133wmyP9oaMnWs1nxy4zUuoCcS47MQr8NPjExxah9ygGeTh'
host = '136.244.89.46'
port = '3889'
user = 'SberUser'
password = '32Xqb%7i8meM7xtoM?Y+'

[prize]
register = 5 # 1000
referral = 5 # 10
master = 5 # 1 000 000
