[winpay]
hour = 11
minute = 30
second = 0
microsecond = 0

timezone = "Europe/Moscow"

[storages]
postgres = "postgres://sbercoin:sbercoin-password@postgres:5432/sbercoin"
redis = "redis://127.0.0.1:6379/0"

